<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>A short vignette; SVD and PCA • PCAworkshop</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="A short vignette; SVD and PCA">
<meta property="og:description" content="PCAworkshop">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-93043521-1"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-93043521-1');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">PCAworkshop</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.2.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/a_Intro.html">A short vignette; SVD and PCA</a>
    </li>
    <li>
      <a href="../articles/b_PCA.html">Principal Component Analysis in R; PCA of covariance or correlation matrix</a>
    </li>
    <li>
      <a href="../articles/c_COA.html">Correspondence Analysis in R</a>
    </li>
    <li>
      <a href="../articles/d_sc_example.html">PCA example: scRNAseq</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/aedin/PCAworkshop">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="a_Intro_files/header-attrs-2.9/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>A short vignette; SVD and PCA</h1>
                        <h4 class="author">Aedin Culhane</h4>
            
            <h4 class="date">May 1, 2021</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/aedin/PCAworkshop/blob/master/vignettes/a_Intro.Rmd"><code>vignettes/a_Intro.Rmd</code></a></small>
      <div class="hidden name"><code>a_Intro.Rmd</code></div>

    </div>

    
    
<div id="r-libraries" class="section level3">
<h3 class="hasAnchor">
<a href="#r-libraries" class="anchor"></a>R libraries</h3>
<p>Install, if necessary, and load necessary libraries and set up R session. If you are running the docker container or using an instance on the orchestra platform, then you should have these libraries installed already.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#if (!requireNamespace("BiocManager", quietly = TRUE)) #install.packages("BiocManager")</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://juba.github.io/explor/">explor</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://pbil.univ-lyon1.fr/ADE-4/">ade4</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tibble.tidyverse.org/">tibble</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/hadley/reshape">reshape2</a></span><span class="op">)</span></code></pre></div>
</div>
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>Principal component analysis (PCA) provides a method for visualizing the distinguishing patterns or information in a dataset. Additional tutorials will provide a more in-depth review of the method, this is just a short and sweet “taster” vignette.</p>
</div>
<div id="dataset-winetasting-in-bordeaux" class="section level1">
<h1 class="hasAnchor">
<a href="#dataset-winetasting-in-bordeaux" class="anchor"></a>Dataset: Winetasting in Bordeaux</h1>
<p>We will use a very simple example dataset of wine-tasting where 200 judges performed a blind tasting of 5 red wines from Bordeaux, scoring each as boring, mediocre, good or excellent.</p>
<p>The dataset is available in the <code>ade4</code> R package:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">bordeaux</span><span class="op">)</span></code></pre></div>
<p>In French wines, table wine has fewer legal restrictions and is cheaper, whereas Cru and Grand Cru wine have more regulation standards and therefore are more expensive.</p>
<div class="figure">
<img src="image/Bordeaux1.png" alt="Figure 1: The bordeaux dataset provides scores from 200 judges in a blind tasting of five different types of red wine from the Bordeaux region of south western parts of France. The judges scored wines as excellent, good, mediocre and boring." width="100%"><p class="caption">
Figure 1: The bordeaux dataset provides scores from 200 judges in a blind tasting of five different types of red wine from the Bordeaux region of south western parts of France. The judges scored wines as excellent, good, mediocre and boring.
</p>
</div>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">bordeaux</span><span class="op">)</span>
<span class="va">bordeaux</span></code></pre></div>
<pre><code>##                    excellent good mediocre boring
## Cru_Bourgeois             45  126       24      5
## Grand_Cru_classe          87   93       19      1
## Vin_de_table               0    0       52    148
## Bordeaux_d_origine        36   68       74     22
## Vin_de_marque              0   30      111     59</code></pre>
<p>Data visualization is important and always a good first step with any dataset, even simple ones. We visualize this data, with a simple barplot, to see the distribution of excellent, good, mediocre and boring scores for each wine. The Grand Cru Classe received more “excellent” scores than the Vin_de_table (table wine).</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#devtools::install_github("gadenbuie/ggpomological")</span>
<span class="co">#install.packages("magick")</span>

<span class="va">df</span><span class="op">&lt;-</span><span class="va">bordeaux</span> <span class="op">%&gt;%</span>
  <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">rownames_to_column</a></span><span class="op">(</span>var<span class="op">=</span><span class="st">"Wine"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">reshape2</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt</a></span><span class="op">(</span><span class="va">.</span>,variable.name<span class="op">=</span><span class="st">"Judge_Score"</span>,
                 value.name<span class="op">=</span><span class="st">"Number"</span><span class="op">)</span>

<span class="va">p</span><span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">df</span>,
           <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">Judge_Score</span>, <span class="va">Number</span>, fill<span class="op">=</span><span class="va">Judge_Score</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>color<span class="op">=</span><span class="st">"black"</span>,stat <span class="op">=</span> <span class="st">"identity"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span><span class="va">Wine</span>, nrow <span class="op">=</span> <span class="fl">2</span><span class="op">)</span><span class="op">+</span>
    <span class="fu">scale_fill_pomological</span><span class="op">(</span><span class="op">)</span><span class="op">+</span>
    <span class="fu">theme_pomological</span><span class="op">(</span><span class="st">"Homemade Apple"</span>, <span class="fl">12</span><span class="op">)</span><span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x<span class="op">=</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,
          legend.position <span class="op">=</span> <span class="st">"bottom"</span>,
          legend.key <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_rect</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span><span class="op">)</span>

 <span class="fu">paint_pomological</span><span class="op">(</span><span class="va">p</span>,res <span class="op">=</span> <span class="fl">110</span><span class="op">)</span> <span class="op">%&gt;%</span>
   <span class="fu">magick</span><span class="fu">::</span><span class="fu"><a href="https://docs.ropensci.org/magick/reference/editing.html">image_write</a></span><span class="op">(</span><span class="st">"barplot-painted.png"</span><span class="op">)</span></code></pre></div>
<div class="figure">
<img src="image/barplot-painted.png" alt="Figure: Visualizing the bordeaux dataset using ggplot and ggtheme pomological" width="100%"><p class="caption">
Figure: Visualizing the bordeaux dataset using ggplot and ggtheme pomological
</p>
</div>
<p>To make it visually interesting we used the <code>ggpomological</code> graphics ggtheme, to display these wine data. The pomology ggtheme and palette evokes the style and colors of old watercolor prints of pomology; a branch of botany that studies and cultivates fruit <a href="https://www.garrickadenbuie.com/project/ggpomological">ggpomological</a>.</p>
</div>
<div id="running-pca" class="section level1">
<h1 class="hasAnchor">
<a href="#running-pca" class="anchor"></a>Running PCA</h1>
<p>We will show two quick approaches to run PCA as seen in Figure 3.</p>
<div id="svd-of-scaled-and-centered-data" class="section level2">
<h2 class="hasAnchor">
<a href="#svd-of-scaled-and-centered-data" class="anchor"></a>1. SVD of scaled and centered data</h2>
<p>We will scale the data with <code>center=TRUE, scale=TRUE</code>,</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">X</span><span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">bordeaux</span>,center <span class="op">=</span> <span class="cn">TRUE</span>, scale <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span></code></pre></div>
<pre><code>##                     excellent       good   mediocre     boring
## Cru_Bourgeois       0.3148138  1.2550661 -0.8434205 -0.6893123
## Grand_Cru_classe    1.4746543  0.5934498 -0.9752049 -0.7549611
## Vin_de_table       -0.9278724 -1.2711053 -0.1054276  1.6576321
## Bordeaux_d_origine  0.0662766  0.0922253  0.4744240 -0.4103050
## Vin_de_marque      -0.9278724 -0.6696359  1.4496290  0.1969464</code></pre>
<p>and apply singular value decomposition (SVD) to the z-score scaled data, X. The SVD was discovered over 100 years ago independently by Eugenio Beltrami (1835–1899) and Camille Jordan (1838–1921). Martin and Porter (2012) wrote a very readable and enjoyable article on the history and application of SVD entitled <a href="https://people.maths.ox.ac.uk/porterm/papers/s4.pdf">‘The Extraordinary SVD’</a>.</p>
<p>SVD matrix decomposition of X will generates 3 matrices, U, D, V where <span class="math display">\[X = U D V'\]</span></p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">s</span><span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/svd.html">svd</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">s</span><span class="op">)</span></code></pre></div>
<pre><code>## List of 3
##  $ d: num [1:4] 3.50 1.71 9.00e-01 8.09e-17
##  $ u: num [1:5, 1:4] -0.4404 -0.5408 0.5595 -0.0253 0.4471 ...
##  $ v: num [1:4, 1:4] -0.535 -0.539 0.422 0.496 0.13 ...</code></pre>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">s</span><span class="op">$</span><span class="va">u</span> <span class="op">%*%</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">d</span><span class="op">)</span> <span class="op">%*%</span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">v</span><span class="op">)</span> <span class="co">#  X = U D V'</span></code></pre></div>
<pre><code>##            [,1]       [,2]       [,3]       [,4]
## [1,]  0.3148138  1.2550661 -0.8434205 -0.6893123
## [2,]  1.4746543  0.5934498 -0.9752049 -0.7549611
## [3,] -0.9278724 -1.2711053 -0.1054276  1.6576321
## [4,]  0.0662766  0.0922253  0.4744240 -0.4103050
## [5,] -0.9278724 -0.6696359  1.4496290  0.1969464</code></pre>
<pre><code>D - singular values.
U - the left singular vectors 
V - the right singular vectors </code></pre>
<p>The rank of X is equal to the number of non-zero singular values, the length(D), is equal to the columns of matrices U,V. The max rank is the number of rows or columns of X, whichever is lower. In this 5x4 dimension matrix, the max rank is 4.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/identical.html">identical</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">d</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/identical.html">identical</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">u</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">v</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">D</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>In statistics and machine learning we talk about finding a low-rank approximation of a matrix, that is a few vectors that approximate the matrix, which can be done by subsetting to a few eigenvectors, or setting eigenvalues to zero.</p>
<p>Finally, the left (U) and right (V) singular vectors <span class="math display">\[ U D V'\]</span> provide a new subspace for the rows and columns of X, respectively.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/identical.html">identical</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">u</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/identical.html">identical</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">v</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div id="eigenvalues" class="section level3">
<h3 class="hasAnchor">
<a href="#eigenvalues" class="anchor"></a>Eigenvalues</h3>
<p>The diagonal matrix <span class="math display">\[diag(s$d)\]</span> contain the singular values, which are always <span class="math display">\[&gt;0\]</span>.</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">d</span><span class="op">)</span></code></pre></div>
<pre><code>##         [,1]     [,2]      [,3]         [,4]
## [1,] 3.50159 0.000000 0.0000000 0.000000e+00
## [2,] 0.00000 1.711166 0.0000000 0.000000e+00
## [3,] 0.00000 0.000000 0.9004307 0.000000e+00
## [4,] 0.00000 0.000000 0.0000000 8.087712e-17</code></pre>
<p>The singular values <code>s$d</code> are square roots of eigenvalues. The eigenvalues which tell how much variance is captured by each component. The maximum number of eigenvalues is the min of the number of row or columns in X.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="op">(</span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">d</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">d</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span><span class="op">)</span><span class="op">*</span><span class="fl">100</span><span class="op">)</span>,<span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 76.63 18.30  5.07  0.00</code></pre>
<p>The first component (PC1, horizontal) captured almost 76.6% of the variance or information in the data and the second component has 18.3%, cumulatively, a plot of PC1 and PC2 would include 95% of the variance in the data. Therefore by droping PC3 and PC4, we have a lower rank representation of X.</p>
</div>
<div id="eigenvector" class="section level3">
<h3 class="hasAnchor">
<a href="#eigenvector" class="anchor"></a>Eigenvector</h3>
<p>Eigenvalues and eigenvectors come in pairs. The columns in U and V are the eigenvectors associated with the singular values in D. The rank is 4, we have four eigenvectors and eigenvalues.</p>
<p>Eigenvalues are ranked, such that the first component PC1 explains the most variance, the second explains the next and so forth. The vectors are orthogonal, uncorrelated. Each tells a different aspect about the data.</p>
<p>So lets look at the singular vectors. The first component, vector PC1 captures almost 77% of the data, but what signal is captures by PC1. Lets look at the first column in the matrices U and V.</p>
<p>The matrix U has the same number rows, representing the 5 wines as the matrix X.</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">rownames</a></span><span class="op">(</span><span class="va">bordeaux</span><span class="op">)</span>, <span class="va">s</span><span class="op">$</span><span class="va">u</span><span class="op">)</span></code></pre></div>
<pre><code>##   rownames.bordeaux.          X1          X2          X3           X4
## 1      Cru_Bourgeois -0.44039631  0.02356098  0.77035252  0.188987607
## 2   Grand_Cru_classe -0.54083076  0.22976639 -0.61518608  0.352593045
## 3       Vin_de_table  0.55947146  0.69035944  0.05163321 -0.005444855
## 4 Bordeaux_d_origine -0.02534875 -0.36052462 -0.14842228 -0.710249368
## 5      Vin_de_marque  0.44710436 -0.58316218 -0.05837736  0.579204642</code></pre>
<p>The number of rows of matrix V equals the number of columns in matrix X; the judges scores (boring/medicore/ood/excellent)</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">bordeaux</span><span class="op">)</span>, <span class="va">s</span><span class="op">$</span><span class="va">v</span><span class="op">)</span></code></pre></div>
<pre><code>##   colnames.bordeaux.         X1         X2          X3        X4
## 1          excellent -0.5345671  0.1302525 -0.74214304 0.3827479
## 2               good -0.5387736 -0.2070736  0.62362747 0.5271929
## 3           mediocre  0.4215187 -0.7790795 -0.23353575 0.4010215
## 4             boring  0.4962691  0.5772261  0.07598379 0.6440136</code></pre>
<p>We will cover more about intepreting PC1, and these scores in the next vignette. But we see PC1 distinguished Boring/medicore from Good/excellent wines.</p>
<ul>
<li>** positive values ** of PC1
<ul>
<li>Boring/medicore judge scores (PC1, right singular vector)</li>
<li>Vin de table (Table Wine) and Vin de marque (Brand Wine) (PC1, left singular vector)</li>
</ul>
</li>
<li>** negative values ** of PC1</li>
<li>Good/excellent scores of the first left singular vectors.</li>
<li>Cru and Grand Cru wines have have negative values on first right singular vectors. Regional Bordeaux wine (Bordeaux d’origine) is close to the origin.</li>
</ul>
<p>If a left singular vector has its sign changed, changing the sign of the corresponding right vector gives an equivalent decomposition. Therefore we look at the direction and distance from the origin, aka the separation either side of the origin.</p>
</div>
</div>
<div id="scores" class="section level2">
<h2 class="hasAnchor">
<a href="#scores" class="anchor"></a>Scores</h2>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pc.scores</span> <span class="op">&lt;-</span> <span class="va">s</span><span class="op">$</span><span class="va">u</span> <span class="op">%*%</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">d</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">pc.scores</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"PC"</span>, <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">pc.scores</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">rownames</a></span><span class="op">(</span><span class="va">bordeaux</span><span class="op">)</span>,<span class="va">pc.scores</span><span class="op">)</span></code></pre></div>
<pre><code>##   rownames.bordeaux.         PC1         PC2         PC3           PC4
## 1      Cru_Bourgeois -1.54208750  0.04031674  0.69364907  1.528477e-17
## 2   Grand_Cru_classe -1.89376778  0.39316845 -0.55393244  2.851671e-17
## 3       Vin_de_table  1.95903989  1.18131964  0.04649213 -4.403642e-19
## 4 Bordeaux_d_origine -0.08876093 -0.61691750 -0.13364398 -5.744293e-17
## 5      Vin_de_marque  1.56557632 -0.99788733 -0.05256477  4.684440e-17</code></pre>
<div id="special-properties-of-svd" class="section level3">
<h3 class="hasAnchor">
<a href="#special-properties-of-svd" class="anchor"></a>Special properties of svd</h3>
<p>Recall SVD decomposes X to:</p>
<p><span class="math display">\[M = U D V^{t}\]</span></p>
<p>where U,V define the left and right singular values</p>
<p>Note that matrices U and V are square orthogonal, that means</p>
<p><span class="math display">\[UU^{t} = I_{p}\]</span> <span class="math display">\[VV^{t} = I_{n}\]</span></p>
</div>
</div>
<div id="using-a-pca-function-in-r" class="section level2">
<h2 class="hasAnchor">
<a href="#using-a-pca-function-in-r" class="anchor"></a>2. Using a PCA function in R</h2>
<p>We can perform the same calculation by as calling a PCA function, for example if we call the R function prcomp</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/prcomp.html">prcomp</a></span><span class="op">(</span><span class="va">bordeaux</span>, scale<span class="op">=</span><span class="cn">TRUE</span>, center<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## Standard deviations (1, .., p=4):
## [1] 1.750795e+00 8.555830e-01 4.502154e-01 4.043856e-17
## 
## Rotation (n x k) = (4 x 4):
##                  PC1        PC2         PC3       PC4
## excellent -0.5345671  0.1302525 -0.74214304 0.3827479
## good      -0.5387736 -0.2070736  0.62362747 0.5271929
## mediocre   0.4215187 -0.7790795 -0.23353575 0.4010215
## boring     0.4962691  0.5772261  0.07598379 0.6440136</code></pre>
<p>The pc.scores manually calculated above is the same as</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/prcomp.html">prcomp</a></span><span class="op">(</span><span class="va">bordeaux</span>, center <span class="op">=</span> <span class="cn">TRUE</span>, scale<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">$</span><span class="va">x</span></code></pre></div>
<pre><code>##                            PC1         PC2         PC3           PC4
## Cru_Bourgeois      -1.54208750  0.04031674  0.69364907  7.763558e-17
## Grand_Cru_classe   -1.89376778  0.39316845 -0.55393244  1.931347e-16
## Vin_de_table        1.95903989  1.18131964  0.04649213 -1.185617e-16
## Bordeaux_d_origine -0.08876093 -0.61691750 -0.13364398 -2.021094e-17
## Vin_de_marque       1.56557632 -0.99788733 -0.05256477 -1.578670e-16</code></pre>
<p>Or we can use the ade4 function dudi.pca. By default dudi.pca uses center = TRUE, scale = TRUE</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bordeaux.pca</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/ade4/man/dudi.pca.html">dudi.pca</a></span><span class="op">(</span><span class="va">bordeaux</span>, scan <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">bordeaux.pca</span><span class="op">)</span></code></pre></div>
<pre><code>## Class: pca dudi
## Call: dudi.pca(df = bordeaux, scannf = FALSE)
## 
## Total inertia: 4
## 
## Eigenvalues:
##     Ax1     Ax2     Ax3 
##  3.0653  0.7320  0.2027 
## 
## Projected inertia (%):
##     Ax1     Ax2     Ax3 
##  76.632  18.301   5.067 
## 
## Cumulative projected inertia (%):
##     Ax1   Ax1:2   Ax1:3 
##   76.63   94.93  100.00</code></pre>
<p>If we plot the output of bordeaux.pca, we see the first component (horizontal), captures most of the information in the dataset, distinguished Vin de table and Vin de marque from the other wines. Whilst Vin de table and Vin de marque were associated with the scores “boring” and “mediocre”. The Grand Cru and Cru wines were “excellent” and “good”</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ade4/man/scatter.html">scatter</a></span><span class="op">(</span> <span class="va">bordeaux.pca</span><span class="op">)</span></code></pre></div>
<p><img src="a_Intro_files/figure-html/unnamed-chunk-18-1.png" width="1000"></p>
<p>We will learn more about the relationship between SVD and PCA, the different R packages that run PCA, in the second vignette Principal Component Analysis in R. We will apply PCA to genomics data in the 4th vignette of the workshop; PCA example: scRNAseq.</p>
<div class="figure">
<img src="image/bordeaux_pca.png" alt="Figure 3: Overview of a PCA of bordeaux dataset" width="100%"><p class="caption">
Figure 3: Overview of a PCA of bordeaux dataset
</p>
</div>
</div>
</div>
<div id="a-few-resources-for-visualization-of-results-explor-pcaexplorer" class="section level1">
<h1 class="hasAnchor">
<a href="#a-few-resources-for-visualization-of-results-explor-pcaexplorer" class="anchor"></a>A few resources for visualization of Results; Explor, pcaExplorer</h1>
<div id="explor" class="section level2">
<h2 class="hasAnchor">
<a href="#explor" class="anchor"></a>Explor</h2>
<p>Julien Barnier’s package <code>explor</code> provides a nice shiny interface to explore matrix factorization results including PCA, Correspondence analysis, or Multiple correspondence analysis and other dimension reduction methods available in R packages <code>ade4</code>, <code>vegan</code>, <code>FactoMineR</code>, <code>GDATools</code>, <code>MASS</code>, <code>stats</code> (<code>prcomp</code> or <code>princomp</code>)</p>
<div class="figure">
<img src="image/explor.png" alt="Explor" width="70%"><p class="caption">
Explor
</p>
</div>
</div>
<div id="pcaexplorer" class="section level2">
<h2 class="hasAnchor">
<a href="#pcaexplorer" class="anchor"></a>pcaExplorer</h2>
<p>Federico Marini and Harald Binder have create a Bioconductor package called <code>pcaExplorer</code></p>
<div class="figure">
<img src="image/pcaExplor.png" alt="PCA of bordeaux dataset" width="70%"><p class="caption">
PCA of bordeaux dataset
</p>
</div>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## R version 4.1.0 (2021-05-18)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 20.04.2 LTS
## 
## Matrix products: default
## BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] reshape2_1.4.4 tibble_3.1.3   ade4_1.7-17    explor_0.3.9   ggplot2_3.3.5 
## [6] dplyr_1.0.7    knitr_1.33    
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.7         tidyr_1.1.3        assertthat_0.2.1   rprojroot_2.0.2   
##  [5] digest_0.6.27      utf8_1.2.2         mime_0.11          plyr_1.8.6        
##  [9] R6_2.5.0           ellipse_0.4.2      evaluate_0.14      highr_0.9         
## [13] pillar_1.6.2       rlang_0.4.11       jquerylib_0.1.4    rmarkdown_2.9     
## [17] pkgdown_1.6.1      textshaping_0.3.5  desc_1.3.0         stringr_1.4.0     
## [21] htmlwidgets_1.5.3  munsell_0.5.0      shiny_1.6.0        compiler_4.1.0    
## [25] httpuv_1.6.1       xfun_0.24          pkgconfig_2.0.3    systemfonts_1.0.2 
## [29] htmltools_0.5.1.1  tidyselect_1.1.1   fansi_0.5.0        crayon_1.4.1      
## [33] withr_2.4.2        later_1.2.0        MASS_7.3-54        grid_4.1.0        
## [37] jsonlite_1.7.2     xtable_1.8-4       gtable_0.3.0       lifecycle_1.0.0   
## [41] DBI_1.1.1          magrittr_2.0.1     formatR_1.11       scales_1.1.1      
## [45] stringi_1.7.3      cachem_1.0.5       fs_1.5.0           promises_1.2.0.1  
## [49] bslib_0.2.5.1      ellipsis_0.3.2     ragg_1.1.3         generics_0.1.0    
## [53] vctrs_0.3.8        scatterD3_1.0.0    RColorBrewer_1.1-2 tools_4.1.0       
## [57] glue_1.4.2         purrr_0.3.4        fastmap_1.1.0      yaml_2.2.1        
## [61] colorspace_2.0-2   memoise_2.0.0      sass_0.4.0</code></pre>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Aedin Culhane, Lauren Hsu.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
